### ISSUE TITLE
CUDA out of memory in test mode

### ISSUE THREAD

**Issue by LeviZhang1996** [PytorchConnectomics/pytorch_connectomics#175]
Hi, my checkpoint is 72MB, test images and masks are 7MB and 61MB.But I got the error.And even I tried to modify the param. as Troublesshooting.md, still failed.
[neuron_seg.yaml](https://github.com/user-attachments/files/23694524/neuron_seg.yaml)

<img width="1319" height="91" alt="Image" src="https://github.com/user-attachments/assets/1593204b-95c6-42eb-8133-a23dde8ccf32" />

**Comment by donglaiw** [comment]
## Fix Applied

This issue has been fixed with multiple memory management improvements in the inference pipeline.

### Problem
CUDA out of memory during test mode due to:
1. Gradients being computed during inference
2. TTA (Test-Time Augmentation) accumulating all predictions in memory before ensembling

### Solution
Updated `connectomics/lightning/inference.py` with:

1. **Added `torch.no_grad()`** to disable gradient computation:
   - In `sliding_window_predict` method
   - In the non-TTA inference path
   - In the TTA loop

2. **Replaced memory-intensive list accumulation with running ensemble**:
   - Instead of storing all 8 TTA predictions and stacking them
   - Now computes running average/min/max incrementally
   - Each prediction is freed after being incorporated

3. **Added explicit memory cleanup**:
   - `del` statements for intermediate tensors
   - Periodic `torch.cuda.empty_cache()` calls

### Recommendations
If you still experience OOM issues, try these config adjustments:

```yaml
inference:
  sliding_window:
    sw_batch_size: 1  # Reduce sliding window batch size
  test_time_augmentation:
    flip_axes: null  # Disable TTA, or use fewer flips: [[2], [3]]
```

### Files Changed
- `connectomics/lightning/inference.py`
